:sparkles: 블루 그린 배포

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+      - feature/SCRUM-66-bluegreenDeploy
   workflow_dispatch:
     inputs:
       name:
@@ -71,6 +72,29 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/nginx
 
+      - name: set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.EC2_HOST }}/env")
+          echo $STATUS
+          if [ $STATUS = 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.EC2_HOST }}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
+
       # ssh 접근 후 docker 이미지 pull 및 컨테이너 재시작
       - name: executing remote ssh commands using password
         uses: appleboy/ssh-action@master
@@ -84,11 +108,38 @@ jobs:
             sudo touch .env
             echo "${{ secrets.ENV }}" | sudo tee .env > /dev/null
             
-            sudo curl -o docker-compose.yml https://raw.githubusercontent.com/ewha-exhibition/Backend/main/docker-compose.yml
+            sudo curl -o docker-compose.yml https://raw.githubusercontent.com/ewha-exhibition/Backend/feature/SCRUM-66-bluegreenDeploy/docker-compose.yml
+            sudo curl -o docker-compose-blue.yml https://raw.githubusercontent.com/ewha-exhibition/Backend/feature/SCRUM-66-bluegreenDeploy/docker-compose-blue.yml
+            sudo curl -o docker-compose-green.yml https://raw.githubusercontent.com/ewha-exhibition/Backend/feature/SCRUM-66-bluegreenDeploy/docker-compose-green.yml
             
             sudo chmod 666 /var/run/docker.sock
             sudo docker rm -f $(docker ps -qa)
             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend
-            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nginx
-            docker compose -f docker-compose.yml --env-file .env up -d
+            docker compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml --env-file .env up -d
             docker image prune -f
+
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.EC2_HOST }}:${{env.STOPPED_PORT}}/actuator/health
+          max-attempts: 3
+          retry-delay: 10s
+
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.EC2_HOST }}
+          key: ${{ secrets.EC2_KEY }}
+          script: |
+            sudo docker exec -i nginx bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+
+      - name: Stop current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.EC2_HOST }}
+          key: ${{ secrets.EC2_KEY }}
+          script: |
+            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+            sudo docker rm ${{env.CURRENT_UPSTREAM}}
